apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-tools-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jgaragorry/k8s-gitops-lab.git
    targetRevision: HEAD
    path: workloads 
  destination:
    server: https://kubernetes.default.svc
    namespace: external-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
